Step1: Check the Yaml files and try to apply the YAML file
       kubectl apply -f <file-name>  # You will get some error

Error:
Error from server (BadRequest): error when creating "postgres-pod.yaml": Pod in version "v1" cannot be handled as a Pod: strict decoding error: unknown field "spec.containers[0].livenessProbe.tcpSocket.command", unknown field "spec.containers[0].readinessProbe.exec.cmd"

Step2: YAML file should be:
apiVersion: v1
kind: Pod
metadata:
  name: postgres-pod
spec:
  containers:
    - name: postgres
      image: postgres:latest
      env:
        - name: POSTGRES_PASSWORD
          value: dbpassword
        - name: POSTGRES_DB
          value: database
      ports:
        - containerPort: 5432
      livenessProbe:
        tcpSocket:
          port: 5432 #Check this section
        initialDelaySeconds: 30
        periodSeconds: 10
      readinessProbe:
        exec:
          command:       # check this section
            - "psql"
            - "-h"
            - "localhost"
            - "-U"
            - "postgres"
            - "-c"
            - "SELECT 1"
        initialDelaySeconds: 5
        periodSeconds: 5

Step3: Apply the file
kubectl apply -f <file-name>  #pod should be up
